import {StyleSheet} from 'react-native';
import {ColorStore} from '../../../mobxStore/colorStore';

export const updateStyle = StyleSheet.create({
  modal: {
    flex: 1,
    backgroundColor: ColorStore().updateModalBackgroundColor.get(),
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    paddingTop: 0,
    width: '95%',
    backgroundColor: ColorStore().updateModalMainContainerColor.get(),
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderRadius: 20,
    elevation: 25,
    height: '100%',
  },
  closeModalDiv: {
    width: '100%',
    alignItems: 'flex-end',
    height: 23,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  closeIcon: {
    alignItems: 'flex-end',
  },
  propertiesDiv: {
    paddingTop: 0,
    backgroundColor: 'beige',
    height: '100%',
    borderWidth: 3,
    borderColor: ColorStore().itemPropertyBorderColor.get(),
    borderRadius: 20,
    elevation: 10,
  },
  issueIdText: {
    fontStyle: 'italic',
    fontWeight: 'bold',
    fontSize: 17,
    color: ColorStore().black.get(),
    alignSelf: 'center',
  },
  secondaryDiv: {
    flexDirection: 'row',
    width: '95%',
    borderWidth: 1,
    borderColor: ColorStore().propertyBorderColor.get(),
    alignSelf: 'center',
    height: '65%',
    borderRadius: 20,
    backgroundColor: ColorStore().updateModalMainContainerColor.get(),
  },
  secondaryDivFirst: {
    marginTop: 3,
    marginLeft: 5,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: ColorStore().propertyBorderColor.get(),
    borderRadius: 20,
    height: '100%',
    width: '65%',
  },
  secondaryDivSecond: {
    marginTop: 3,
    marginHorizontal: 2,
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: ColorStore().itemPropertyBorderColor.get(),
    borderRadius: 20,
    height: '100%',
    width: '32%',
    backgroundColor: ColorStore().updateModalSecondaryContainercolor.get(),
  },
  updateButton: {
    width: 60,
    borderWidth: 2,
    borderColor: ColorStore().itemPropertyBorderColor.get(),
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: ColorStore().updateButtonbackgroundColor.get(),
  },
});
